# Generated by Django 6.0 on 2026-01-08 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_coordinators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='qr_code_url',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AddField(
            model_name='album',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='managed_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
