# Generated by Django 6.0 on 2026-01-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='creator',
            new_name='created_by',
        ),
    ]
