# Generated by Django 6.0 on 2026-01-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='verb',
            new_name='message',
        ),
    ]
